# Generated by Django 2.2.6 on 2019-11-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('birtday', models.DateField()),
                ('address', models.TextField(max_length=200)),
                ('phonenum1', models.IntegerField(default=0, max_length=13)),
                ('phonenum2', models.IntegerField(default=0, max_length=13, null=True)),
                ('identityCard', models.IntegerField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('note', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
