# Generated by Django 2.2.6 on 2019-11-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phonenum1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenum2',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
