# Generated by Django 2.2.8 on 2020-03-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200219_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(max_length=20)),
                ('shift', models.CharField(default=1, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.TextField(blank=True, default='', max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='student.Area')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='student.SystemLevel')),
            ],
        ),
        migrations.AlterField(
            model_name='fee',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classer', to='student.Classes'),
        ),
        migrations.AlterField(
            model_name='studentinclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Classes'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.AddField(
            model_name='classes',
            name='members',
            field=models.ManyToManyField(through='student.StudentInClass', to='student.Student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='student.Teacher'),
        ),
    ]
