# Generated by Django 2.2.8 on 2020-05-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200522_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Thuộc khu vực'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fee',
            field=models.IntegerField(default=0, verbose_name='Phí sách'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên sách'),
        ),
        migrations.AlterField(
            model_name='book',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Chú thích'),
        ),
        migrations.AlterField(
            model_name='cambridgelevel',
            name='fee',
            field=models.IntegerField(default=0, verbose_name='Lệ phí thi'),
        ),
        migrations.AlterField(
            model_name='cambridgelevel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cấp bậc Cambrige'),
        ),
        migrations.AlterField(
            model_name='cambridgelevel',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Chú thích'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên lớp'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Chú thích'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='room',
            field=models.CharField(max_length=20, verbose_name='Phòng học'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='shift',
            field=models.CharField(default=1, max_length=20, verbose_name='Ca học'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='identity_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='CMND / CMT'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_learning',
            field=models.BooleanField(default=True, verbose_name='Còn học ?'),
        ),
        migrations.AlterField(
            model_name='systemlevel',
            name='fee',
            field=models.IntegerField(default=0, verbose_name='Học phí'),
        ),
        migrations.AlterField(
            model_name='systemlevel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cấp độ'),
        ),
        migrations.AlterField(
            model_name='systemlevel',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Chú thích'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='identity_number',
            field=models.CharField(default='', max_length=10, verbose_name='CMND / CMT'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_male',
            field=models.BooleanField(default=False, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên giáo viên'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='note',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Chú thích'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='', max_length=12, verbose_name='Số điện thoại'),
        ),
    ]
