# Generated by Django 2.2.6 on 2019-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191101_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identityCard',
            field=models.IntegerField(null=True),
        ),
    ]
