# Generated by Django 2.2.6 on 2019-11-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20191101_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identityCard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenum2',
            field=models.IntegerField(default=0),
        ),
    ]
