# Generated by Django 2.2.8 on 2020-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200522_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fee_photo',
            field=models.TextField(default='', verbose_name='Phí sách photo'),
        ),
        migrations.AddField(
            model_name='systemlevel',
            name='book_description',
            field=models.TextField(blank=True, verbose_name='Mô tả sách'),
        ),
        migrations.AddField(
            model_name='systemlevel',
            name='certificate',
            field=models.TextField(default='', max_length=5, verbose_name='Chứng chỉ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(default=60000, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fee',
            field=models.IntegerField(default=0, verbose_name='Phí sách GỐC'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_learning',
            field=models.BooleanField(default=True, verbose_name='Đang học ?'),
        ),
        migrations.AlterField(
            model_name='systemlevel',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_male',
            field=models.BooleanField(default=False, verbose_name='Giới tính: Nam'),
        ),
    ]
