# Generated by Django 2.2.6 on 2019-11-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20191101_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('fee', models.IntegerField(default=0)),
                ('note', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CambridgeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('fee', models.IntegerField(default=0)),
                ('note', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('gender', models.BooleanField(default=False)),
                ('birthday', models.DateField()),
                ('address', models.TextField(default='', max_length=100)),
                ('phonenum', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('identityCard', models.CharField(default='', max_length=10)),
                ('note', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='identityCard',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='SystemLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('fee', models.IntegerField(default=0)),
                ('note', models.TextField(default='', max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='student.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('room', models.CharField(default='', max_length=20)),
                ('shift', models.CharField(default=1, max_length=20)),
                ('dayStart', models.DateField()),
                ('dayEnd', models.DateField()),
                ('note', models.TextField(default='', max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='student.Area')),
                ('systemlevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemlevels', to='student.SystemLevel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='student.Teacher')),
            ],
        ),
    ]
