# Generated by Django 2.2.6 on 2019-11-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20191102_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowPayBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('releaseDay', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('note', models.TextField(default='', max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Book')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCambridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examday', models.DateField()),
                ('waitResult', models.BooleanField(default=True)),
                ('passed', models.BooleanField(default=False)),
                ('note', models.TextField(default='', max_length=100)),
                ('cambridgeLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.CambridgeLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('releaseDay', models.DateField(auto_now_add=True)),
                ('note', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentWaitClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='identityCard',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenum1',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenum2',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phonenum',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.AddField(
            model_name='studentwaitclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='studentwaitclass',
            name='systemLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.SystemLevel'),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='gift',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='examcambridge',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='borrowpaybook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
