# Generated by Django 2.2.6 on 2019-11-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20191105_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(default=0)),
                ('receipt', models.IntegerField()),
                ('paymentday', models.DateField(auto_now_add=True)),
                ('note', models.TextField(default='', max_length=100)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
