# Generated by Django 2.2.6 on 2019-11-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20191118_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birtday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
